### 팔로워
POST localhost:8080/relation/follow
Content-Type: application/json

{
  "userId": 1,
  "targetUserId": 2
}

### 팔로워 취소
POST localhost:8080/relation/unfollow
Content-Type: application/json

{
  "userId": 1,
  "targetUserId": 2
}
